---
output: html_document
---

## SDS 323 Exercises 1
### Kyle Carter, Jacob Rachiele, Crystal Tse, Jinfang Yan
### 2/14/2020

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load required packages
library(mosaic)
library(tidyverse)
```
## Problem 1: Flights at ABIA

## Problem 2: Regression Practice (Creatinine)



## Problem 3: Green Buildings

## Problem 4: Milk Prices

```{r}
# Read the data file
milk = read.csv("data/milk.csv")
```

Find the relationship between and f(p) = Q. (Q = aP^b)  (P is x)
```{r}
ggplot(data = milk) +
  geom_point(aes(x = price, y = sales)) +
  geom_smooth(mapping = aes(x = price, y = sales))
```

Recognize this is not a linear regression. This is a demand function. Therefore, we use Power law.

```{r}
mod1 = lm(log(sales) ~ log(price), data = milk)
coef(mod1)
#log(Q) = 4.7 - 1.62 * log(P)
# beta 0 is log(alpha)
#Q = e ^ 4.7 * P ^ -1.62 = 110 * P ^ -1.62
plot(log(sales) ~ log(price), data = milk)
abline(mod1, col = "red")
```

```{r}
# Now: N = (P - C) * 110 * P ^ -1.62
# to find the optimal profit
curve((x-1)*110*x^(-1.62), from = 1, to = 9)
#Zoom in 
curve((x-1)*110*x^(-1.62), from = 2.5, to = 2.7)
```

```{r}
# Another method:
# f(x) maximum at x, the log(f(x)) maximum at x
mod2 = lm(log(N) ~ 2)
milk <- milk %>% 
  mutate(C = 1) %>% 
  mutate(N = (price - C) * sales)
```


```{r}
ggplot(data = milk) +
  geom_point(aes(x = sales, y = N)) +
  geom_smooth(mapping = aes(x = sales, y = N) )
```

```{r}
mod1 = lm(log(N) ~ log(price), data = milk)
ggplot(data = milk) + 
  geom_point(aes(x = price, y = N)) 
```
